stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/sklearn/train/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Train Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- dvclive/plots/sklearn/test/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Test Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
