stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
