stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
plots:
- dvclive/plots/sklearn/train/confusion_matrix.json:
    template: simple
    x: fpr
    y: tpr
    title: Train Confusion Matrix
    x_label: False Positive Rate
    y_label: True Positive Rate
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
